services:
  api:
    container_name: api
    build: ./api
    env_file:
      - ./api/.env        # ou remets ".env" si tu gardes le .env Ã  la racine
    volumes:
      - ./api:/app
      - /app/node_modules
      - ./web:/web
    command: sh -c "npm run dev"

  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    depends_on:
      - api
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/dist:/usr/share/nginx/html:ro      # si "root /usr/share/nginx/html/dist;"
      - ./certs:/etc/nginx/certs:ro
    command: ["nginx", "-g", "daemon off;"]

  web-build:
    image: node:20-bookworm
    working_dir: /web
    volumes:
      - ./web:/web
    command: sh -lc "npm ci && npm run build"


  prometheus:
    build:
      context: ./monitoring/prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - "9090:9090" #allow access to Prometheus web
    volumes:
      - prometheus_data:/prometheus #persistent data for prometheus
    restart: always
  grafana:
    container_name: grafana
    depends_on: #needs prometheus to be running first
      - prometheus
    ports:
      - "3000:3000"
    build:
      context: ./monitoring/grafana
      dockerfile: Dockerfile
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - grafana_data:/var/lib/grafana #persistent data for grafana
      - grafana_data:/grafana/data #persistent data for grafana
    restart: always

  cadvisor: #monitor docker containers
    image: gcr.io/cadvisor/cadvisor:latest #use latest cadvisor image (no dockerfile, maybe add one later)
    container_name: cadvisor
    # ports:
    #   - "8080:8080"
    volumes: #necessary volumes for cadvisor to monitor docker and system stats
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      #- /var/lib/docker:/var/lib/docker:ro #installation with apt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/snap/docker/common/var-lib-docker:/var/lib/docker:ro #installation with snap
    restart: always

volumes:
  grafana_data:
  prometheus_data:
